services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data           # ★ 読み書き
    environment:
      - RUST_LOG=info
      - DATABASE_URL=sqlite:///app/data/data.db   # ★ ここを三本スラッシュに
